### ISSUE TITLE
Anchor links to headers inside zpages

### ISSUE THREAD

**Issue by zulamit** [free2z/zuu#35]
Hello!  

I have a new idea and is: what if we have an option within the editing tools that links a word with a specific place in the same zpage.

For example: When someone makes a page in Spanish, and then put something like: "To go to the english version, you can click here" and then we move to that part of the zpage.

I mean, link that word to the place on the page where the english version starts.

This is just an example but it can be used for multiple situations.

It would be very useful to have it in the default options.

I hope it is possible. Thank you very much for all the new features you have added.

Free2z rocks!

**Comment by skyl** [comment]
yep; we should add something like that - anchor links. IIRC github does it automatically

### Should be a link?

I tried to see if this was already available, something like https://stackoverflow.com/a/15843220/177293 but I'll have to add it to the free2z-flavored markdown - you can see it doesn't work here: 

https://free2z.com/flavored-markdown#code-blocks

it works on the new docsite which is in docusaurus; shouldn't be too hard

https://free2z.com/docs/creators/creating-a-zpage#finished-zpage

It's not altogether trivial because it needs a little script to scroll sth like

https://ericdcobb.medium.com/scrolling-to-an-anchor-in-react-when-your-elements-are-rendered-asynchronously-8c64f77b5f34

Notes:

+        "rehype-autolink-headings": "^6.1.1",
+        "rehype-slug": "^5.1.0",

```
-            rehypePlugins={[rehypeKatex, rehypePrism]}
+            // https://github.com/rehypejs/rehype-autolink-headings#example-content
+            rehypePlugins={[
+                rehypeKatex, rehypePrism,
+                rehypeSlug,
+                [rehypeAutolinkHeadings, {
+                    behavior: "append",
+                    content() {
+                        return [
+                            h('span', '#')
+                        ]
+                    },
+                }]
+            ]}
```

I tried to see if I could do it real quick but it's going to take a little more effort. I'll try again at some point.

**Comment by skyl** [comment]
Thanks to 1337bytes, th8s should be fixed. There might be some improvements left tondo but we could open a new issue for those improvements.
