### ISSUE TITLE
Delete uploaded media button to media management

### ISSUE THREAD

**Issue by zerodartz** [free2z/zuu#49]
Right now cant find a way to delete uploaded media. Uploaded many copies of things for testing and would be nice to delete them so server has more room again.

**Comment by zerodartz** [comment]
Also since noticed this: "You get one gigabyte of storage for free, and each additional gigabyte can be purchased for 10 2Zs (in-app currency)." from docs.

It would be nice to see a storage graph/bar of how much storage in use and how much free and/or in MB and %.

**Comment by skyl** [comment]
> Also since noticed this: "You get one gigabyte of storage for free, and each additional gigabyte can be purchased for 10 2Zs (in-app currency)." from docs.
> 
> It would be nice to see a storage graph/bar of how much storage in use and how much free and/or in MB and %.

we haven't implemented charging for storage yet; but, if we do (likely), we will definitely have some sort of total used and estimated charges.

I think we pay 3-5 cents per month per gigabyte, so I wouldn't worry about it too much since you are super-ultra platinum early adopter D:. But, yes, delete would be good just for organization.

**Comment by skyl** [comment]
tracking this and others here: https://github.com/orgs/free2z/projects/37/views/1 Let us know what else it would need to be beyond world class

**Comment by skyl** [comment]
Deleting media has been added.
