### ISSUE TITLE
Infinite Vertical Scroll feature(s)

### ISSUE THREAD

**Issue by Cryptonativa** [free2z/zuu#58]
The caruousel concept is really cool however I think it would be even better to have an infinite feed instead of just a carousel.  This will give the opportunity to showcase more creators in a more dynamic way since people will continue to swipe up vertically to see the next content, increasing engagement and the overall excitement of the app.  
I want to be able to swipe up vertically to change the slide on mobile, instated on sliding to left and ride, like twitter, tiktok, facebook, instagram... Basically one carrousel infinite feed. 
![Not easy to play with on mobile](https://user-images.githubusercontent.com/128416795/232249030-4365221d-7421-4368-88e4-2646c0d03097.png)

**Comment by skyl** [comment]
It's not really an either/or situation. Someone should go ahead and implement a tiktok/reddit/youtube view and, if it's better than whatever is at `/`, then that view could become the home page. It should gracefully handle anonymous and logged-in users because the primary case for `/` will be users who are not logged in. Most sites use some other route for "home" for logged-in users. I made a survey of popular sites and TikTok, Reddit and YouTube were the only ones with infinite vertical scroll at `/` for logged-out users.

### Twitter

Comparing twitter `/home` feed to `/`

One thing to recognize is that your Twitter screenshot is from the feed of a logged in user, not the home page for a user who is not authenticated. On the web version, your screenshot is `twitter.com/home`, not `twitter.com/`. Twitter doesn't present an infinite scroll on their home page for a user who is not authenticated. This is what it looks like:

<img width="925" alt="Screenshot 2023-04-16 at 2 48 20 PM" src="https://user-images.githubusercontent.com/61438/232344358-d3179a3b-6080-425b-ab16-24e1b1279fae.png">

You can get to some doom scrolling with a search:

<img width="817" alt="Screenshot 2023-04-16 at 2 15 00 PM" src="https://user-images.githubusercontent.com/61438/232342522-82a203a6-c4ce-41c3-ad6f-5843823e8e82.png">

It's cool. We could also replace the traditional pagination on our `/find` with an infinite scroll.

### Facebook

Does Facebook drop you directly into doom-scroll mode when you go to facebook.com? No, you basically can't do anything without logging in, I guess.

<img width="816" alt="Screenshot 2023-04-16 at 2 18 32 PM" src="https://user-images.githubusercontent.com/61438/232342707-acbf4d69-84f8-42c3-b907-5f9fd8e02ae8.png">

Well, I found an infinite scroll without being logged in to Facebook by using Google. It's laughably unresponsive and looks like crap on slim width screen:

<img width="807" alt="Screenshot 2023-04-16 at 2 20 44 PM" src="https://user-images.githubusercontent.com/61438/232343025-086f528b-0b9d-4628-a7eb-b49112200c4c.png">

Not a great example.

Let's look at a few other sites when you visit `/` without logging in.

### Netflix

<img width="791" alt="Screenshot 2023-04-16 at 2 24 18 PM" src="https://user-images.githubusercontent.com/61438/232343226-197f0a90-0134-4f4f-b9a7-ae7942402bf4.png">

### Github

<img width="792" alt="Screenshot 2023-04-16 at 2 26 39 PM" src="https://user-images.githubusercontent.com/61438/232343342-865c8bd7-3720-4497-bd2d-fbba9201ebda.png">

### New York Times

<img width="793" alt="Screenshot 2023-04-16 at 2 27 26 PM" src="https://user-images.githubusercontent.com/61438/232343380-5f90827a-c524-4c7b-9f8e-2094a1777621.png">

### GoFundMe

<img width="925" alt="Screenshot 2023-04-16 at 2 28 23 PM" src="https://user-images.githubusercontent.com/61438/232343427-4c0865ff-f640-4e6b-b7cf-e550598bd13d.png">

### Patreon

<img width="924" alt="Screenshot 2023-04-16 at 2 29 10 PM" src="https://user-images.githubusercontent.com/61438/232343459-d21630cd-c18a-4ca7-bfa5-eadd1defd3f0.png">

### TikTok

Tiktok does drop you right into their famous doom-scroll:

<img width="924" alt="Screenshot 2023-04-16 at 2 31 37 PM" src="https://user-images.githubusercontent.com/61438/232343574-8ec2de17-40fc-49c0-b6da-915653ab883a.png">

### Youtube

As far as infinite vertical scroll at `/` for logged-out users, I think YouTube wins. It looks elegant at all screen widths.

I think TikTok, Reddit and Twitter looks sort of cluttered and janky by comparison.

<img width="1101" alt="Screenshot 2023-04-16 at 3 24 21 PM" src="https://user-images.githubusercontent.com/61438/232346040-8745686c-4ee8-4718-9683-27ba62fb7d6e.png">

### Instagram

<img width="930" alt="Screenshot 2023-04-16 at 2 39 24 PM" src="https://user-images.githubusercontent.com/61438/232343903-9b1b7e06-bcd4-49a0-8b8c-778dd57de64c.png">

### Medium

Medium does give you what sort of feels like an infinite scroll but it does end after a few loads.

<img width="930" alt="Screenshot 2023-04-16 at 2 41 55 PM" src="https://user-images.githubusercontent.com/61438/232344028-728ddffb-a68e-4f7b-9229-56bbee799cee.png">

### Substack

<img width="928" alt="Screenshot 2023-04-16 at 2 43 17 PM" src="https://user-images.githubusercontent.com/61438/232344092-48f87527-e803-4c25-8b74-addccb8e003e.png">

### Hulu

<img width="925" alt="Screenshot 2023-04-16 at 2 46 01 PM" src="https://user-images.githubusercontent.com/61438/232344245-0481a254-8384-4a8b-abb1-85e01d357e12.png">

### Gumroad

<img width="926" alt="Screenshot 2023-04-16 at 2 46 54 PM" src="https://user-images.githubusercontent.com/61438/232344280-60775531-421b-4117-849d-405ff743c930.png">

### Reddit

Reddit does have a pretty good doom scroll right at `/` whether you are logged in or not.

https://www.reddit.com/

### Summary of survey

Tiktok, Reddit and YouTube are the only sites from the list that put an infinite scroll at the `/` route for anonymous users. They are cool. Someone can do that at some point for free2z. Likely `/` will turn into a bit of a marketing splash page like most of the other sites in the world. But, I could see doing like Reddit/TikTok/Youtube and dropping people right into an infinite vertical feed.

## What is the proper analogy?

Something to recognize about twitter, facebook, etc is that the investment in an individual post is basically zero, you just scroll by, seeing the entire post and you don't really consider it or invest any time into it - scroll, like, keep scrolling. Deciding to read a zpage or check out what a free2z creator is up to (and maybe chip in some funds) is arguably more akin to choosing a movie to watch on Netflix or Hulu than scrolling by tweets.

Netflix doesn't have a vertical doomscroll anywhere that I'm aware, certainly not at `/`. But, once you log in, you are sent to `/browse` and you have a bunch of rows with horizontal scroll.

<img width="1081" alt="Screenshot 2023-04-16 at 2 59 14 PM" src="https://user-images.githubusercontent.com/61438/232344998-816aa3e7-ab17-4548-a070-505e6f7b499b.png">

This is sort of what I had in mind when I started playing with the carousel idea. 

One thing to think about with free2z is that there are different types of objects - creators, zpages, storytimes, media, video, audio, images, current livestreams, comments ... - all of these could be independently doom-scrolled. But, trying to mix and match different objects in a single doom scroll is pretty challenging technically - probably for little benefit (mixing videos and storytimes and zpages and creators ... ?). If we have enough content over time then I think the feed of audio files will be separate from the feed of video files, will be separate from the free of zpages, etc. I imagine the first infinite scroll feed on free2z will be a feed of things people you subscribe to did.

But, basically we could have 10 vertical scrolls and none of them be at `/` and we still have carousels at `/` with a marketing page. There are a lot of possible futures though. I wish I had more help with the software development.

**Comment by skyl** [comment]
https://user-images.githubusercontent.com/61438/232372048-3e27a017-e10b-45d6-8a79-145bd0541275.mp4


https://user-images.githubusercontent.com/61438/232372154-a5cb48da-7060-4162-a7d9-086ee92be58b.mp4

**Comment by skyl** [comment]
We aren't on here (yet). But, check out the layout :thinking:

<img width="1158" alt="Screenshot 2023-04-21 at 9 10 13 PM" src="https://user-images.githubusercontent.com/61438/233761701-de9c125b-c1a1-48d2-bf8d-fe1775c48bbc.png">

**Comment by skyl** [comment]
https://play.google.com/store/search?q=free2z.com&c=apps

**Comment by skyl** [comment]
Check out https://free2z.com/converse and see what you think. I think we need more granular issues for different kinds of feeds. There is another infinite scroll at https://free2z.cash/events/

So, that's 2 infinite scrolls. I think there could also be: AI conversations, zPages, Creators ... we could have a single scroll that mixes in different types of objects. But, I kinda' like that Free2Z is straightforward and not so magical ... still open to ideas but we should move to more specific issues?
